### ISSUE TITLE
360 videos not working on iphone

### ISSUE THREAD

**Issue by thatpassesfor** [xrchat/kxr-dev#31]
to reproduce:  go to beta.kaixr.world, do not log in, point towards video.  enter video.  

expected: video to play
actual: black screen with a vr button. 

![image](https://user-images.githubusercontent.com/63731634/79662936-baec4780-8182-11ea-877f-97308120ec70.png)

**Comment by andyps** [comment]
@mohrtw We need to create m3u8 hls playlists alongside with mpd files.
Shaka Player cannot use mpd on iPhone devices https://github.com/google/shaka-player#platform-and-browser-support-matrix because Media Source Extensions API (which is needed) is not supported there https://caniuse.com/#feat=mediasource

**Comment by thatpassesfor** [comment]
Just tested on dev server as of PR https://github.com/xrchat/xrchat-client/pull/109, still not working on IOS

**Comment by dmitrizagidulin** [comment]
Working now on dev server, closing.
